version: '3.8'

services:
  # Cấu hình cho PostgreSQL
  postgres_db:
    image: postgres:14.1-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: my_postgres_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # Cấu hình cho MySQL
  mysql_db:
    image: mysql:8.0
    container_name: local-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_mysql_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  # Cấu hình cho Redis
  redis:
    image: redis:7-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  mysql_data:
  redis_data: