spring.application.name=RelearnSpringBoot
server.port=8081
# setting postgres with spring
spring.datasource.user.jdbc-url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.user.username=postgres
spring.datasource.user.password=123456

spring.datasource.product.jdbc-url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.product.username=postgres
spring.datasource.product.password=123456

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=100

# cho phep flyway tu dong chay migration khi start app
spring.flyway.enabled=true

# chon lua schema de xu dung flyway de chay script
spring.flyway.default-schema=my_schema

#che do baseline
#False: mac dinh: se bao loi neu db da co du lieu nhung chua co lich su Flyway
#True: se tu dong tao bang lich su va coi db hien tai la phien ban goc v1 neu gap db cu
spring.flyway.baseline-on-migrate=false
spring.flyway.baseline-version=0

#duong dan toi thu muc chua cac file sql migration
#spring.flyway.locations=classpath:db/migration


