spring:
  datasource:
    user:
      jdbc-url: ${PROD_DB_URL}
      username: ${PROD_DB_USERNAME}
      password: ${PROD_DB_PASSWORD}
    product:
      jdbc-url: ${PROD_DB_URL}
      username: ${PROD_DB_USERNAME}
      password: ${PROD_DB_PASSWORD}
server:
  port: ${PROD_DB_PORT:8081}