spring.application.name=RelearnSpringBoot
server.port=8081

# setting postgres with spring
spring.datasource.url=jdbc:postgresql://localhost:5432/pgDataLearn
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate cho Postgres dialect spring 6 auto choose dialect optimize with db, don't choose it here
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# setting MySql with spring
#spring.datasource.url=jdbc:mysql://localhost:3306/myDataLearn?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA & Hibernate cho MySQL
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true